os:
  - Visual Studio 2015

install:
  - set PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%
  - appveyor DownloadFile "https://raw.githubusercontent.com/swig/cccl/master/cccl"
  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
  - cmd: bash -cvx "if (appveyor-retry true 2>/dev/null || test -x \"$(which appveyor-retry 2>/dev/null)\") && test -x \"$(which pacman)\" && test -n \"$(ls m*.db*)\"; then (appveyor-retry pacman -Syuu --needed --noconfirm --noprogressbar --ask=127) && (appveyor-retry pacman -S --noconfirm autoconf automake libtool gtk-doc mingw-w64-x86_64-pkg-config mingw-w64-x86_64-harfbuzz mingw-w64-x86_64-fribidi mingw-w64-x86_64-freetype); fi"
  - cmd: bash -cvx "if (appveyor-retry true 2>/dev/null || test -x \"$(which appveyor-retry 2>/dev/null)\") && test -x \"$(which vcpkg)\"; then (vcpkg update && vcpkg upgrade && (appveyor-retry vcpkg install gtk) && vcpkg install gtk3 && vcpkg install gtkmm); fi"
  - cmd: bash -cvx "if test -x \"$(which scoop 2>/dev/null)\"; then (scoop bucket add extras && scoop install extras/gtk-sharp); fi"
  - cmd: bash -cvx "if test -x \"$(which choco)\"; then (choco update || choco upgrade); (choco install gtk-runtime || choco install --pre gtk-runtime); fi"
  - cmd: bash -cvx "if test -x \"$(which winget 2>/dev/null)\"; then winget install -e --id Mono.gtksharp; fi"

build_script:
  - set CC=cccl
  - set CXX=cccl
  - set LD=cccl
  - set PKG_CONFIG_PATH=%PKG_CONFIG_PATH%:/mingw64/lib/pkgconfig
  - bash -cvx "cp -v cccl /usr/bin"
  - bash -cvx "exec 0</dev/null; ./autogen.sh"
  - bash -cvx "exec 0</dev/null; ./configure"
  - bash -cvx "exec 0</dev/null; make CFLAGS='/W4 /WX /wd4068'"

test_script:
  - bash -cvx "make check || (cat \"$(find . -name '*.log')\" && stat Makefile)"

# disable automatic tests
test: off
