dist: xenial

os:
  - linux
  - osx

language: c

matrix:
  include:
    - os: linux
      after_success:
        - bash .ci/deploy-docs.sh

    - os: linux
      compiler: clang

    - os: osx
      before_install:
        - export HOMEBREW_NO_EMOJI=1 HOMEBREW_BOOTSNAP=1 HOMEBREW_CURL_VERBOSE=1 HOMEBREW_VERBOSE=1 HOMEBREW_VERBOSE_USING_DOTS=1
        - export XML_CATALOG_FILES="/usr/local/etc/xml/catalog" # for the docs
        - export GIT_CURL_VERBOSE=1 && env | sort | uniq
        - gem install bundle

before_script:
  - ./autogen.sh
  - ./configure --enable-gtk-doc --disable-Werror

script:
  - make check || (cat `find . -name '*.log'` && false)
  - make distcheck

addons:
  apt:
    packages:
      - libfreetype6-dev
      - libharfbuzz-dev
      - libfribidi-dev
      - gtk-doc-tools
  homebrew:
    packages:
      - freetype
      - fribidi
      - gtk-doc
      - harfbuzz
