name: cooljeanius/libraqm
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.0.0
    - run: apt-get -y install libfreetype6-dev libharfbuzz-dev libfribidi-dev gtk-doc-tools
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if test -e /usr/local/etc/xml/catalog; then export XML_CATALOG_FILES="/usr/local/etc/xml/catalog"; fi
    - run: "./autogen.sh"
    - run: "./configure --enable-gtk-doc"
    - run: make check || (cat `find . -name '*.log'` && false)
    - run: make distcheck
    - run: bash .ci/deploy-docs.sh
      if: "${{ success() }}"
